services:
  backend-blue:
    image: backend-app:1.1
    #container_name: backend-blue
    environment:
      - PORT=3000
      - APP_VERSION=blue
    expose:
      - "3000"
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    external: true
