services:
  backend-green:
    image: backend-app:1.1
    #container_name: backend-green
    environment:
      - PORT=3000
      - APP_VERSION=green
    expose:
      - "3000"
    networks:
      - backend-network
    restart: always
networks:
  backend-network:
    external: true

